In [1]:
import polars as pl

In [9]:
df = pl.read_parquet("../data/results.parquet")

In [4]:
value_mask = df["col_value"].list.eval(pl.element().str.contains("(?i)temp")).list.any()
name_mask = df["col_name"].list.eval(pl.element().str.contains("(?i)temp")).list.any()
temp_rows = df.filter(value_mask | name_mask)
temp_rows

shape: (450, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ bioprojec ┆ col_name  ┆ col_value ┆ statistic ┆ … ┆ count_pos ┆ mean_nega ┆ std_negat ┆ count_ne │
│ t         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ itive     ┆ tive      ┆ ive       ┆ gative   │
│ ---       ┆ list[str] ┆ list[str] ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆ i32       ┆ f64       ┆ f64       ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ PRJNA8243 ┆ ["treatme ┆ ["CO2:    ┆ 0.0       ┆ … ┆ 1         ┆ 0.050764  ┆ null      ┆ 1        │
│ 13        ┆ nt_attrib ┆ 400 µam;  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ "]        ┆ temperatu ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re: 1…    ┆           ┆   ┆           ┆           ┆           ┆          │
│ PRJNA8243 ┆ ["treatme ┆ ["CO2:    ┆ 1.0       ┆ … ┆ 1         ┆ 0.04205   ┆ null      ┆ 1        │
│ 13        ┆ nt_attrib ┆ 1000 µam; ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ "]        ┆ temperatu ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ re: …     ┆           ┆   ┆           ┆           ┆           ┆          │
│ PRJNA6727 ┆ ["culture ┆ ["40      ┆ 117.0     ┆ … ┆ 10        ┆ 8.594688  ┆ 14.173015 ┆ 26       │
│ 11        ┆ _conditio ┆ degrees C ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ns_attrib ┆ high temp ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ "]        ┆ eature…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ PRJNA5591 ┆ ["temp_at ┆ ["18C"]   ┆ 4.0       ┆ … ┆ 4         ┆ 0.057806  ┆ null      ┆ 1        │
│ 95        ┆ trib"]    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PRJNA5591 ┆ ["temp_at ┆ ["10C"]   ┆ 0.0       ┆ … ┆ 1         ┆ 0.1365    ┆ 0.094023  ┆ 4        │
│ 95        ┆ trib"]    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ PRJNA3275 ┆ ["temp_at ┆ ["18C"]   ┆ 3.0       ┆ … ┆ 2         ┆ 0.627721  ┆ 0.640336  ┆ 2        │
│ 78        ┆ trib"]    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PRJNA3275 ┆ ["temp_at ┆ ["29C"]   ┆ 1.0       ┆ … ┆ 2         ┆ 2.722456  ┆ 3.261247  ┆ 2        │
│ 78        ┆ trib"]    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PRJNA2768 ┆ ["temp_at ┆ ["15      ┆ 229.0     ┆ … ┆ 16        ┆ 3.546391  ┆ 5.307784  ┆ 30       │
│ 27        ┆ trib"]    ┆ deg"]     ┆           ┆   ┆           ┆           ┆           ┆          │
│ PRJNA2768 ┆ ["temp_at ┆ ["30      ┆ 121.0     ┆ … ┆ 6         ┆ 4.493459  ┆ 6.164518  ┆ 40       │
│ 27        ┆ trib"]    ┆ deg"]     ┆           ┆   ┆           ┆           ┆           ┆          │
│ PRJNA2768 ┆ ["temp_at ┆ ["37      ┆ 274.0     ┆ … ┆ 24        ┆ 4.193657  ┆ 5.987239  ┆ 22       │
│ 27        ┆ trib"]    ┆ deg"]     ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [16]:
# sort by p-value
temp_rows_sorted = temp_rows.sort("pvalue")
temp_rows_sorted.write_parquet("../data/temp_results.parquet")

In [ ]:
# get rows where bioproject is PRJNA615972 
rows = df.filter(pl.col("bioproject") == "PRJNA615972")
# get rows where col_name is temp_attrib
rows = rows.filter(pl.col("col_name") == ["temp_attrib"])
rows

shape: (3, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ bioprojec ┆ col_name  ┆ col_value ┆ statistic ┆ … ┆ count_pos ┆ mean_nega ┆ std_negat ┆ count_ne │
│ t         ┆ ---       ┆ ---       ┆ ---       ┆   ┆ itive     ┆ tive      ┆ ive       ┆ gative   │
│ ---       ┆ list[str] ┆ list[str] ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆ i32       ┆ f64       ┆ f64       ┆ i32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ PRJNA6159 ┆ ["temp_at ┆ ["36C"]   ┆ 724.0     ┆ … ┆ 29        ┆ 1.560375  ┆ 1.091907  ┆ 57       │
│ 72        ┆ trib"]    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PRJNA6159 ┆ ["temp_at ┆ ["28C"]   ┆ 1070.0    ┆ … ┆ 30        ┆ 1.213959  ┆ 0.600904  ┆ 56       │
│ 72        ┆ trib"]    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PRJNA6159 ┆ ["temp_at ┆ ["20C"]   ┆ 669.0     ┆ … ┆ 27        ┆ 1.530262  ┆ 1.093847  ┆ 59       │
│ 72        ┆ trib"]    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [15]:
# sort all temp rows by bioproject
rows = temp_rows_sorted.sort("bioproject")
rows.write_parquet("../data/temp_results_sorted.parquet")